# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt


      # Step 3: run task2  tests
      - run:
          name: Run Task 2 unit tests
          command: |
            . venv/bin/activate
            python3 -m unittest --verbose tests.test_extract tests.test_database
            python3 main.py inspect --name Halley
            python3 main.py inspect --pdes 433
            python3 main.py inspect --verbose --name Ganymed


      # Step 4: run task3  tests
      - run:
          name: Run Task 3 unit tests
          command: |
            . venv/bin/activate
            python3 -m unittest tests.test_query tests.test_limit
            python3 main.py query --date 2020-01-01
            python3 main.py query --start-date 2020-01-01 --end-date 2020-12-31
            python3 main.py query --start-date 2020-01-01 --end-date 2020-12-31 --max-distance 0.1
            python3 main.py query --start-date 2020-01-01 --end-date 2020-12-31 --min-distance 0.3
            python3 main.py query --start-date 2020-01-01 --end-date 2020-12-31 --max-velocity 50
            python3 main.py query --start-date 2020-01-01 --end-date 2020-12-31 --min-velocity 25
            python3 main.py query --min-diameter 0.5 --max-diameter 0.6 --not-hazardous
            python3 main.py query --max-distance 0.1 --min-velocity 35 --min-diameter 2.5 --hazardous

      # # Step 5: run full unit tests
      # - run:
      #     name: Run  Full unit tests
      #     command: |
      #       . venv/bin/activate
      #       python3 -m unittest

      # # Step 6: run output file tests
      # - run:
      #     name: Run Task Full unit tests
      #     command: |
      #       . venv/bin/activate
      #       python3 main.py query --date 2020-01-01 --limit 5 --outfile results.csv
      #       python3 main.py query --date 2020-01-01 --limit 5 --outfile results.json
      #       python3 main.py query --start-date 2020-01-01 --end-date 2020-12-31 --hazardous --min-diameter 0.25 --max-distance 0.1 --limit 5 --outfile results.json
         
      # # Step 4 run API Tests 
      # - run:
      #     name: Run API test methods
      #     command: |
      #       . venv/bin/activate
      #         pyhttptest execute apitest.json
          
      # # Genarate output CSV File
      # - run:
      #     name: Generate Output CSV File
      #     command: |
      #       . venv/bin/activate
      #       rm -rf  data/ou*
      #       ./wp.sh input.csv output.csv
      #       echo "******************************"
      #       echo "Content of /data directory"
      #       echo "******************************"
      #       mv data/out* data/output.csv
      #       ls -ltrhi  data/
      #       echo "******************************"
      #       echo "Content of the Output CSV File"
      #       echo "******************************"
      #       cat data/out*
      #       echo "___________S U C C E S S !!!_________________________"